# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-19 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_scores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nfl_scores.Team'),
        ),
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Week',
        ),
    ]
